name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ilhanbzn/githubactions

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:v1.0.1, ${{ env.IMG_NAME }}:latest

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ env.IMG_NAME }}:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
                composer install
                npm install
                npm run production
                python ./hello.py