name: Github Actions Project 
on: 
  push:
    branches: [ "main" ]
    tags: [ "v1.0.2" ]

jobs:
  nax-githubactions: 
    name: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3
    
      - name: Login to Dockerhub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with: 
          images: ilhanbzn/githubactions
          tags: |
            type=ref,event=tags
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

        
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          